### ISSUE TITLE
Out of Date

### ISSUE THREAD

**Issue by pinkp** [silverstripe/silverstripe-lessons-v4#113]
Is it just me or are these lesson out of date?

**Comment by sensenel** [comment]
the whole silverstripe thing feels out of date! ... sry, but ... pff

**Comment by GuySartorelli** [comment]
I'm going to close this issue as it doesn't point to a specific part of the lessons that needs updating. Feel free to open a new issue which points to specific problems in the lessons - and as always PRs are welcome.
