### ISSUE TITLE
Please update the lessons!

### ISSUE THREAD

**Issue by MichaelNZ85** [silverstripe/silverstripe-lessons-v4#116]
These lessons are really out of date. Setting up the dev environment didn't go as per lesson 0 (the installer has been removed since the lesson was written) and now I'm stuck on the Working with multiple templates lesson due to an issue with namespaces.

Please could we get some up-to-date lessons with the latest version???

**Comment by GuySartorelli** [comment]
That would be great, I agree - and it's definitely on the (very long) list of things we want to get around to. But we have limited resourcing.
This is an open source resource, so anyone can commit pull requests to help us get these updated.
I'm going to close this issue now as it doesn't point to a specific problem in the lessons. Feel free to open a new issue for a specific problem with the lessons, if an issue doesn't exist for that problem already.
