### ISSUE TITLE
Bug in lesson-05 (or Silver Stripe)

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-lessons-v4#48]
At end of lesson-05 try adding a new page that is a child of "Travel Guides".  

At "Choose Page Type" 'Article Holder' is available but 'Article Page' is greyed out.

**Comment by imandings** [comment]
@worikgh did you set Travel Guides to Article Holder? You can't put an Article Page in, till the parent has been defined Article Holder.
