### ISSUE TITLE
Lesson 20's SQL Query is too inefficient; causes PHP timeout.

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-lessons-v4#60]
It may not be the query (13 rows with the provided database), but the iteration of it's results.
It seems that maybe `while($record = $result->nextRecord())` may no longer do as expected, and in any case take far too long to do it's work, reaching the timeout of 30 seconds before the requested page can be rendered.

Below is an example, although the code is modified to demonstrate the issue:

```
Fatal error: Maximum execution time of 30 seconds exceeded in /usr/local/var/www/ss4/mysite/code/ArticleHolder.php on line 58
[Alert] Maximum execution time of 30 seconds exceeded
GET /ss4/travel-guides/
Line 58 in /usr/local/var/www/ss4/mysite/code/ArticleHolder.php

Source
49             ->setSelect([])
50             ->selectField("DATE_FORMAT(`Date`,'%Y_%M_%m')", "DateString")
51             ->setFrom($tableName)
52             ->setOrderBy("DateString", "ASC")
53             ->setDistinct(true);
54         $result = $query->execute();
55 //die($query->sql());
56         if ($result) {
57             $c=0;
*58             while($thing = $result->nextRecord()) {
59                 $c++;
60             }
61             die("$c");
62             while ($record = $result->nextRecord()) {
63                 list($year, $monthName, $monthNumber) = explode('_', $record['DateString']);
64                 $list->push(ArrayData::create([
Trace
```
(no trace).
The `die` is never hit. When commenting the loop, it is.

**Comment by theloverkills** [comment]
This can be fixed by simply changing the while loop to a forloop:

`while ($record = $result->nextRecord()) {`

Change into:

`foreach($result as $record) {`

**Comment by dhensby** [comment]
Care to PR? :)

**Comment by imandings** [comment]
Looks like this was changed in #64 which was merged in.
