### ISSUE TITLE
Little typo in lesson 7 'SetWidth(750) -> ScaleWidth(750)'

### ISSUE THREAD

**Issue by pieht** [silverstripe/silverstripe-lessons-v4#71]
https://www.silverstripe.org/learn/lessons/v4/working-with-files-and-images-1

"On ArticlePage.ss, the photo is larger, and it's important that we show all of its content, since this is the detail view. Let's use SetWidth(750) for this one."

SetWidth(750) -> ScaleWidth(750)

And maybe it would be a good idea to mention that SetWidth was the old #ss3 method.

Thanks and Cheese! :)

**Comment by robbieaverill** [comment]
Thanks for reporting, would you like to make a PR to fix?

**Comment by pieht** [comment]
That's what I wanted to do in the first place. But I couldn't find the text here on GitHub :(

**Comment by pieht** [comment]
Ah sorry, I just found it and made a PR
