### ISSUE TITLE
Lesson rewrite broke URLs

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-lessons-v4#84]
https://docs.silverstripe.org/en/4/lessons/ points to non-existant URLs. That's bad for two reasons: Devs need to hunt down the right page, and any SEO juice we've gotten on the old URLs will be gone. Can you please fix this, @unclecheese 

## Pull Requests 
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8790

**Comment by dnsl48** [comment]
that's one of todos from https://github.com/silverstripe/silverstripe-lessons-v4/issues/83

**Comment by ScopeyNZ** [comment]
I saw the PR - didn't have time to test it but I did update the TODO issue to tick this item and reference this issue.

**Comment by robbieaverill** [comment]
PR is merged
